# Site settings
title: nuaawao
header-img: img/home-bg.jpg
email: missqso@gmail.com
description: "nuaawao，喵奴，steam +1 狂魔，不玩 APP 会死"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: ltscnrm
github_username:  missqso
facebook_username:  graykx

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
