# Site settings
title: nuaawao
header-img: img/bg.jpg
email: missqso@gmail.com
description: "nuaawao，猫奴，steam +1 狂魔"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: ltscnrm
github_username:  missqso
facebook_username: graykx

# Build settings
markdown: kramdown
highlighter: pygments
permalink: '/:year/:month/:title'
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
timezone: '+0800'

kramdown:
  input: GFM